### PR TITLE
release 2.0.4

### PR DESCRIPTION
**Pull request by flodnv**
forgot this in https://github.com/Expensify/Bedrock-PHP/pull/200

### CODE REVIEW

**Review by iwiznia — APPROVED** [review]
You created the tag too?
Also lol 
image

Just in case not merging, but go ahead if all is ready

**Comment by flodnv** [comment]
Yes  I created the tag, got confused between 3 and 4 because 3 already existed as a tag though the version was 2 🤷

**Comment by flodnv** [comment]
Looks like I fucked up something and I don't know what...

In Web-E, updated composer.json to have `"expensify/bedrock-php": "2.0.4`

then:
```
vagrant@expensidev2004:/vagrant/Web-Expensify$ composer update expensify/bedrock-php
Loading composer repositories with package information
Updating dependencies                                 
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires expensify/bedrock-php 2.0.4, found expensify/bedrock-php[dev-tweak_composer_for_lebp-stack, dev-ionatan_randomwait_restart, dev-dsilva_addingVersionMismatchHandling, dev-main, dev-revert-182-ionatan_dontwaitforchildren, dev-package_name_to_lowercase, 1.0.0, ..., 1.9.20, 2.0.0, 2.0.1, 2.0.2, 2.0.3] but it does not match the constraint.

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
vagrant@expensidev2004:/vagrant/Web-Expensify$ 
```

Do you have any idea?

**Comment by iwiznia** [comment]
Yes, you created the tag wrong. [The 2.0.4 tag](https://github.com/Expensify/Bedrock-PHP/tree/2.0.4) has [composer with version 2.0.2](https://github.com/Expensify/Bedrock-PHP/blob/2.0.4/composer.json#L5)

**Comment by flodnv** [comment]
Damn, I always fuck this up.

**Comment by iwiznia** [comment]
Not sure why, there's a script for it... maybe update the instructions in the readme?

**Pull request merged**
