### PR TITLE
Add retryAfter to queueJob function

### PR DESCRIPTION
**Pull request by mattabullock**
We need to add the retryAfter param to queueJob for an upcoming change on web. It already exists in CreateJob so we just need to accept the param and pass it through.

### CODE REVIEW

**Comment by mattabullock** [comment]
I'm more than happy to just switch all the calls to CreateJob instead of QueueJob. Is there a historical reason for silencing errors?

**Comment by iwiznia** [comment]
No idea, my guess is that we call this on jobs that if don't get created, we don't care.

**Comment by mattabullock** [comment]
Gonna close this and just migrate the QueueJob calls to CreateJob.

**Comment by mattabullock** [comment]
@iwiznia we're overruling you, don't wanna open up spots in the code where we can exit early and create more errors for jobs we previously didn't care about.

**Comment by iwiznia** [comment]
I am not sure I follow what you said, but go ahead.

**Pull request merged**
